# Generated by Django 5.1.4 on 2024-12-11 14:11

import authors.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), authors.validators.AlphaValidator()])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), authors.validators.AlphaValidator()])),
                ('passcode', models.CharField(help_text='Your passcode must be a combination of 6 digits', max_length=10, validators=[authors.validators.DigitValidator()])),
                ('pets_number', models.PositiveSmallIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
