# Generated by Django 5.1.4 on 2024-12-11 14:20

import authors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(help_text='Your passcode must be a combination of 6 digits', max_length=6, validators=[authors.validators.DigitValidator()]),
        ),
    ]
